import { makeDateAndTime } from './js/app'
import { generate } from './js/app'
import { postData } from './js/app'
import { getData } from './js/app'
import { getWeather } from './js/app'
import { colorChange } from './js/app'
import { iconColor } from './js/app'

import './styles/base.scss'
import './styles/header.scss'
import './styles/trip-form-output.scss'
import './styles/trip-form.scss'
