import { makeDateAndTime } from './js/handleSubmit'
import { generate } from './js/handleSubmit'
import { getData } from './js/handleSubmit'
import { getUserData } from './js/savedTripsView'
import { viewNewTrip } from './js/viewNewTrip'
import { appendItem } from './js/addPackingItem'
import { togglePacked } from './js/addPackingItem'
import { viewSavedTrips } from './js/savedTripsView'
import { addSavedTrip } from './js/savedTripsView'
import { updateServer } from './js/saveTrip'

import './styles/base.scss'
import './styles/header.scss'
import './styles/trip-form-output.scss'
import './styles/trip-form.scss'
