import { makeDateAndTime } from './js/app'
import { generate } from './js/app'
import { postData } from './js/app'
import { getData } from './js/app'
import { getUserData } from './js/savedTripsView'
import { getWeatherBit } from './js/getWeatherbit'
import { getGeonames } from './js/getGeonames'
import { updateUI } from './js/updateUI'
import { colorChange } from './js/app'
import { iconColor } from './js/app'
import { appendItem } from './js/addPackingItem'
import { togglePacked } from './js/addPackingItem'
import { viewSavedTrips } from './js/savedTripsView'

import './styles/base.scss'
import './styles/header.scss'
import './styles/trip-form-output.scss'
import './styles/trip-form.scss'
